//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickWorkshop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ordersdetail
    {
        public int OrderId { get; set; }
        public int ServiceId { get; set; }
        public double Price { get; set; }
    
        public virtual order order { get; set; }
        public virtual service service { get; set; }
    }
}
