//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickWorkshop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class product
    {
        public product()
        {
            this.orderpdetails = new HashSet<orderpdetail>();
        }
    
        public int ProductId { get; set; }
        [Required(ErrorMessage = "Este campo no puede estar vacio")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Este campo no puede estar vacio")]
        public int Quantity { get; set; }
        [DataType(DataType.Currency)]
        [Required(ErrorMessage = "Este campo no puede estar vacio")]
        public double Price { get; set; }
        public string AddPError { get; set; }

        public virtual ICollection<orderpdetail> orderpdetails { get; set; }
    }
}
