//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickWorkshop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        public user()
        {
            this.orders = new HashSet<order>();
        }
    
        public int UserID { get; set; }
        [DataType(DataType.EmailAddress)]
        [Required(ErrorMessage = "Este campo no puede estar vacio")]
        public string Email { get; set; }
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Este campo no puede estar vacio")]
        public string Password { get; set; }
        public string Name { get; set; }
        public string Position { get; set; }
        public string Status { get; set; }
        public string LoginError { get; set; }
        

        public virtual ICollection<order> orders { get; set; }
    }
}
